<?php

namespace AppBundle\Repository;

/**
 * SubscriptionPolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionPolicyRepository extends \Doctrine\ORM\EntityRepository
{
}
