app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\UserController

roles:
    type:     rest
    resource: AppBundle\Controller\RoleController

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
