# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        auth_token_user_provider:
            id: auth_token_user_provider
        login:
            entity:
              class:    AppBundle\Entity\User
              property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        doc:
            pattern: ^/doc
            security: false
        token:
            pattern: ^/auth-token
            security: false

        registration:
            pattern: ^/registration
            security: false

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~


        login:
             pattern:    ^/
             http_basic: ~
             provider: login
             form_login:
                      login_path: login
                      check_path: login

